name: Build the zip

on:
  workflow_dispatch: # only need to run manually  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - run: python3 build.py output
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: bundle.zip
        # A file, directory or wildcard pattern that describes what to upload
        path: output/*
        # The desired behavior if no files are found using the provided path.
